server:
  port: 8080
spring:
  jpa.hibernate.ddl-auto: update
  datasource:
    url: jdbc:mysql://taskit-db.cm5yfi6qhccs.ap-northeast-2.rds.amazonaws.com:3306/taskit
    username: admin
    password: admin!23
  resources:
    cache:
      cachecontrol:
        no-cache: true
